<a href="https://colab.research.google.com/github/abelwalekhwa/AI_Modeling_MUK/blob/main/Practice_Week2_12052023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Data Visualization
import math as m
m.sqrt(48) # Running square root of 48
m.pi




3.141592653589793

In [6]:
#Arrays
import numpy as np
#creating one dimesion array
a = np.array([1,2,3], int)
print(a)


[1 2 3]


In [7]:
# Creating multi-dimesion array
b = np.array([[1,2,3,4],[6,7,8,9]])
print(b)

[[1 2 3 4]
 [6 7 8 9]]


In [8]:
#shapes of array
b.shape


(2, 4)

In [10]:
#changing the shapes of array
b.reshape((4,2))

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [11]:
#Transpose function
b.transpose()

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [12]:
#Array mathematics
x= np.array([1,2,3],int)
y= np.array([5,6,9],int)
x+y

array([ 6,  8, 12])

In [15]:
#Array iteraction in x
x= np.array([1,2,3],int)
for i in x: 
  print(i)


1
2
3


In [16]:
#Array items summation
x.sum()


6

In [17]:
#Array items product
x.prod()


6

In [18]:
#Pandas (Panel Data Library)
import pandas as pd
a = [1,3,5]
print(a)

[1, 3, 5]


In [20]:
#Create data frame
dataframe = pd.Series(a)
print(dataframe)

0    1
1    3
2    5
dtype: int64


In [23]:
#creating your own index
dataframe = pd.Series(a, index = ['w','x','y'])
print(dataframe)

w    1
x    3
y    5
dtype: int64


In [25]:
data = {
    "Calories" : [429, 349, 679],
    "Duration" : [69, 40, 50]
}
df = pd.dataframe(data, index =["Day1", "Day2", "Day3"])
print(df)

AttributeError: ignored